# Generated by Django 6.0.7 on 2026-07-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Имя пользователя",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=128, verbose_name="Пароль пользователя"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Имя пользователя"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="colors",
                        to="main_app.user",
                        verbose_name="Пользователи",
                    ),
                ),
            ],
        ),
    ]
