# Generated by Django 6.0.7 on 2026-07-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="clicks",
            field=models.IntegerField(default=0, verbose_name="Кол-во кликов"),
        ),
    ]
