# Generated by Django 6.0.7 on 2026-07-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_user_clicks"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="price",
            field=models.IntegerField(default=100, verbose_name="Цена цвета"),
        ),
    ]
