# Generated by Django 6.0.7 on 2026-08-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
